// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webmvc.Data;

#nullable disable

namespace webmvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417063403_Create_table_Chitietdhs")]
    partial class Create_table_Chitietdhs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("webmvc.Models.Entities.Chitietdh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonhangMadonhang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Madonhang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Masanpham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SanphamMasanpham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Soluong")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonhangMadonhang");

                    b.HasIndex("SanphamMasanpham");

                    b.ToTable("Chitietdhs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Donhang", b =>
                {
                    b.Property<string>("Madonhang")
                        .HasColumnType("TEXT");

                    b.Property<string>("KhachhangMaKhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("TEXT");

                    b.HasKey("Madonhang");

                    b.HasIndex("KhachhangMaKhachHang");

                    b.ToTable("Donhangs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Faculty", b =>
                {
                    b.Property<string>("FacultyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Khachhang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhachHang");

                    b.ToTable("Khachhangs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Sanpham", b =>
                {
                    b.Property<string>("Masanpham")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<int>("Soluongton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Masanpham");

                    b.ToTable("Sanphams");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Student", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentCode");

                    b.HasIndex("FacultyId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Chitietdh", b =>
                {
                    b.HasOne("webmvc.Models.Entities.Donhang", "Donhang")
                        .WithMany("Chitietdhs")
                        .HasForeignKey("DonhangMadonhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webmvc.Models.Entities.Sanpham", "Sanpham")
                        .WithMany("ChiTietdhs")
                        .HasForeignKey("SanphamMasanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Donhang", b =>
                {
                    b.HasOne("webmvc.Models.Entities.Khachhang", "Khachhang")
                        .WithMany("Donhangs")
                        .HasForeignKey("KhachhangMaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Student", b =>
                {
                    b.HasOne("webmvc.Models.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Donhang", b =>
                {
                    b.Navigation("Chitietdhs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Khachhang", b =>
                {
                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Sanpham", b =>
                {
                    b.Navigation("ChiTietdhs");
                });
#pragma warning restore 612, 618
        }
    }
}
