// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webmvc.Data;

#nullable disable

namespace webmvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513040000_CreateTableBooks")]
    partial class CreateTableBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("webmvc.Models.Buoi12.Devicetype", b =>
                {
                    b.Property<int>("DevicetypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevicetypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DevicetypeId");

                    b.ToTable("Devicetypes");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevicetypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipmentId");

                    b.HasIndex("DevicetypeId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockin", b =>
                {
                    b.Property<int>("StockinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.HasKey("StockinId");

                    b.ToTable("Stockins");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockindt", b =>
                {
                    b.Property<int>("StockindtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockinId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("StockindtId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("StockinId");

                    b.ToTable("Stockindts");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockout", b =>
                {
                    b.Property<int>("StockoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("TEXT");

                    b.HasKey("StockoutId");

                    b.ToTable("Stockouts");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockoutdt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockoutId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("StockoutId");

                    b.ToTable("Stockoutdts");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Suplier", b =>
                {
                    b.Property<int>("SuplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SuplierId");

                    b.ToTable("Supliers");
                });

            modelBuilder.Entity("webmvc.Models.Buoi13.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Chitietdh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonhangMadonhang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Madonhang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Masanpham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SanphamMasanpham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Soluong")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonhangMadonhang");

                    b.HasIndex("SanphamMasanpham");

                    b.ToTable("Chitietdhs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenPhong")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Donhang", b =>
                {
                    b.Property<string>("Madonhang")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("TEXT");

                    b.HasKey("Madonhang");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("Donhangs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Faculty", b =>
                {
                    b.Property<string>("FacultyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Khachhang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhachHang");

                    b.ToTable("Khachhangs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPhong")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Sanpham", b =>
                {
                    b.Property<string>("Masanpham")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gia")
                        .HasColumnType("TEXT");

                    b.Property<int>("Soluongton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Masanpham");

                    b.ToTable("Sanphams");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Student", b =>
                {
                    b.Property<string>("StudentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentCode");

                    b.HasIndex("FacultyId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Equipment", b =>
                {
                    b.HasOne("webmvc.Models.Buoi12.Devicetype", "Devicetype")
                        .WithMany("Equipments")
                        .HasForeignKey("DevicetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devicetype");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockindt", b =>
                {
                    b.HasOne("webmvc.Models.Buoi12.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webmvc.Models.Buoi12.Stockin", "Stockin")
                        .WithMany("Stockindts")
                        .HasForeignKey("StockinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Stockin");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockoutdt", b =>
                {
                    b.HasOne("webmvc.Models.Buoi12.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webmvc.Models.Buoi12.Stockout", "Stockout")
                        .WithMany("Stockoutdts")
                        .HasForeignKey("StockoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Stockout");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Chitietdh", b =>
                {
                    b.HasOne("webmvc.Models.Entities.Donhang", "Donhang")
                        .WithMany("Chitietdhs")
                        .HasForeignKey("DonhangMadonhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webmvc.Models.Entities.Sanpham", "Sanpham")
                        .WithMany("ChiTietdhs")
                        .HasForeignKey("SanphamMasanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Donhang", b =>
                {
                    b.HasOne("webmvc.Models.Entities.Khachhang", "Khachhang")
                        .WithMany("Donhangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Person", b =>
                {
                    b.HasOne("webmvc.Models.Entities.Department", "Department")
                        .WithMany("Persons")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Student", b =>
                {
                    b.HasOne("webmvc.Models.Entities.Faculty", "Faculty")
                        .WithMany("Students")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Devicetype", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockin", b =>
                {
                    b.Navigation("Stockindts");
                });

            modelBuilder.Entity("webmvc.Models.Buoi12.Stockout", b =>
                {
                    b.Navigation("Stockoutdts");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Department", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Donhang", b =>
                {
                    b.Navigation("Chitietdhs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Faculty", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Khachhang", b =>
                {
                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("webmvc.Models.Entities.Sanpham", b =>
                {
                    b.Navigation("ChiTietdhs");
                });
#pragma warning restore 612, 618
        }
    }
}
